### ISSUE TITLE
The player can move outside playing area, enemies cannot follow. 

### ISSUE THREAD

**Issue by Coralon** [AIESydProgYr12021/aie_cpd-firstomars#3]
**Description -** When the player avatar moves outside the playing area enemies cannot follow making it very simple to defeat them.
**Priority -** B High Priority
**Platforms -** WebGL
**Build -** Build 2 (08/09/21)
**Reproduction -** Start game, trigger enemy detection, leave playing area. See attached video.

https://user-images.githubusercontent.com/45445873/132448338-be8aab9e-fc2b-4b79-a340-abd915182be0.mp4

**Comment by firstomars** [comment]
Sorted out in build 13/09 AM.
